# prometheus config demo
# please edit /etc/prometheus/prometheus.yml to change config

global:
  scrape_interval:     15s
  # compute rule interval
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    # this will be coverage global
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']