#!/bin/bash

if [ `whoami` != "root" ]; then
    echo "you must run by root!"
    exit 1 
fi

sudo useradd --no-create-home --shell /usr/sbin/nologin prometheus

sudo mkdir /etc/prometheus
sudo mkdir /var/lib/prometheus
sudo chown prometheus:prometheus /etc/prometheus
sudo chown prometheus:prometheus /var/lib/prometheus


if [ -f "prometheus-2.19.3.linux-amd64.tar.gz" ]; then
    tar -zxvf prometheus-2.19.3.linux-amd64.tar.gz
else
    wget https://github.com/prometheus/prometheus/releases/download/v2.19.3/prometheus-2.19.3.linux-amd64.tar.gz
    tar -zxvf prometheus-2.19.3.linux-amd64.tar.gz
fi

sudo cp -r prometheus-2.19.3.linux-amd64/* /etc/prometheus


sudo chown -R prometheus:prometheus /etc/prometheus


rm -r prometheus-2.19.3.linux-amd64

sudo cp -v prometheus /etc/init.d/

sudo service prometheus start
sudo chkconfig --add prometheus
sudo chkconfig prometheus on