#!/bin/bash

if [ `whoami` != "root" ]; then
    echo "you must run by root!"
    exit 1 
fi

sudo useradd --no-create-home --shell /bin/false node_exporter

if [ -f "node_exporter-1.0.1.linux-amd64.tar.gz" ]; then
    tar -zxvf node_exporter-1.0.1.linux-amd64.tar.gz
else
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar -zxvf node_exporter-1.0.1.linux-amd64.tar.gz
fi

sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin
sudo chown node_exporter:node_exporter /usr/local/bin/node_exporter

rm -r node_exporter-1.0.1.linux-amd64

sudo cp node_exporter.service /etc/systemd/system/

sudo systemctl daemon-reload
sudo systemctl start node_exporter
sudo systemctl enable node_exporter